server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:zonedb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

iot-api:
  base-url: "http://104.211.95.241:8080/api"
  username: "admin"
  password: "password"
